name: throttling_example
description: Demonstrates how to use the "throttling" and "debouncing" async helper classes with listeners
version: 1.0.0
homepage: https://github.com/quantosapplications/throttling
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  throttling:
    path: ../

dev_dependencies:
  effective_dart: ^1.3.1
