name: throttling_example
description: Demonstrates how to use the "throttling" and "debouncing" async helper classes with listeners
version: 1.0.0
author: plugfox <plugfox@gmail.com>
homepage: https://github.com/quantosapplications/throttling

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  throttling:
    path: ../

dev_dependencies:
  effective_dart: ^1.3.1
