name: throttling
description: Contain "throttling" and "debouncing" async helper classes with listeners

version: 2.0.0-dev.1
homepage: https://github.com/PlugFox/throttling
repository: https://github.com/PlugFox/throttling

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.0.0
