name: throttling
description: contain "throttling" and "debouncing" async helper classes with listeners for flutter
version: 0.9.1
homepage: https://github.com/PlugFox/throttling
repository: https://github.com/PlugFox/throttling

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  