name: throttling
description: Contain "throttling" and "debouncing" async helper classes with listeners

version: 1.0.0-dev
homepage: https://github.com/PlugFox/throttling
repository: https://github.com/PlugFox/throttling

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
