name: throttling
description: Contain "throttling" and "debouncing" async helper classes with listeners

version: 1.0.0
homepage: https://github.com/PlugFox/throttling
repository: https://github.com/PlugFox/throttling

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  effective_dart: ^1.3.1
  test_coverage: ^0.5.0
  test: ^1.0.0
