name: throttling
description: contain "throttling" and "debouncing" async helper classes with listeners for flutter
version: 0.9.0
author: plugfox <plugfox@gmail.com>
homepage: https://github.com/PlugFox/throttling

environment:
  sdk: ">=2.0.0 <3.0.0"
